# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Docker Login
      run: docker login -u ${{ secrets.DOCKER_USER_NAME }} -p ${{secrets.DOCKER_PASSWORD}}

    - name: Build Docker Image
      run: docker build -t js55998/htmlapp .
    
    - name: Publish Image to Docker Hub
      run: docker push js55998/htmlapp:latest 

  deploy:
    needs: build
    runs-on: aws-ec2
    steps:
      - name: Pull Docker Image
        run: docker pull js55998/htmlapp:latest
    
      - name: Delete Old Container 
        run: docker rm -f htmlContainer
    
      - name: Run Docker Container
        run: docker run -d -p 5000:80 --name htmlContainer js55998/htmlapp
    
